version: "3.9"

services:
  backend:
    container_name: lumencodex-backend
    build:
      context: ./LumenCodex.Server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./LumenCodex.Server:/app
      - /app/obj
      - /app/bin
      - ~/Documents:/courses_root

  frontend:
    container_name: lumencodex-frontend
    build:
      context: ./LumenCodex.Client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./LumenCodex.Client:/app
      - /app/node_modules
